import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const sourceSansProLight = localFont({
  src: "../fonts/source-sans-pro.light.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="da">
      <body
        className={`${sourceSansProLight.className} flex min-h-screen flex-col bg-[#f0f0f0] antialiased`}
      >
        <Header />
        <main className="mx-auto w-full max-w-6xl flex-1 space-y-8 p-4 pt-12">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
